language: minimal

services:
  - docker

script:
  - docker --version
  - docker build -t simple-reverse-proxy .
  - docker tag simple-reverse-proxy yesenarman/udacity-simple-reverse-proxy:latest

deploy:
  provider: script
  script: bash docker_push.sh
  on:
    branch: master
